/*==============================================================*/
/* DBMS name:      MySQL 5.0                                    */
/* Created on:     20/07/03 00:44:41                            */
/*==============================================================*/


/*==============================================================*/
/* Table: SYS_USER                                              */
/*==============================================================*/
CREATE TABLE SYS_USER
(
   ID                   BIGINT NOT NULL AUTO_INCREMENT,
   USERNAME             VARCHAR(64),
   PASSWORD             VARCHAR(128),
   REAL_NAME            VARCHAR(64),
   GENDER               TINYINT,
   PHONE_NUMER          VARCHAR(32),
   EMAIL                VARCHAR(64),
   LAST_LOGIN_TIME      DATETIME,
   PWD_UPDATE_TIME      DATETIME,
   FILE_ID              BIGINT,
   ORG_ID               BIGINT,
   REMARK               VARCHAR(256),
   ISVALID              TINYINT,
   CREATE_TIME          DATETIME,
   CREATE_BY            BIGINT,
   UPDATE_TIME          DATETIME,
   UPDATE_BY            BIGINT,
   PRIMARY KEY (ID)
);

ALTER TABLE SYS_USER COMMENT '用户表';

ALTER TABLE SYS_USER MODIFY COLUMN ID BIGINT COMMENT 'id';

ALTER TABLE SYS_USER MODIFY COLUMN USERNAME VARCHAR(64) COMMENT '用户名';

ALTER TABLE SYS_USER MODIFY COLUMN PASSWORD VARCHAR(128) COMMENT '密码';

ALTER TABLE SYS_USER MODIFY COLUMN REAL_NAME VARCHAR(64) COMMENT '姓名';

ALTER TABLE SYS_USER MODIFY COLUMN GENDER TINYINT COMMENT '性别 1：男 2：女';

ALTER TABLE SYS_USER MODIFY COLUMN PHONE_NUMER VARCHAR(32) COMMENT '联系电话';

ALTER TABLE SYS_USER MODIFY COLUMN EMAIL VARCHAR(64) COMMENT '邮箱';

ALTER TABLE SYS_USER MODIFY COLUMN LAST_LOGIN_TIME DATETIME COMMENT '上次登录时间';

ALTER TABLE SYS_USER MODIFY COLUMN PWD_UPDATE_TIME DATETIME COMMENT '密码更新时间';

ALTER TABLE SYS_USER MODIFY COLUMN FILE_ID BIGINT COMMENT '头像文件id';

ALTER TABLE SYS_USER MODIFY COLUMN ORG_ID BIGINT COMMENT '组织id';

ALTER TABLE SYS_USER MODIFY COLUMN REMARK VARCHAR(256) COMMENT '备注';

ALTER TABLE SYS_USER MODIFY COLUMN ISVALID TINYINT COMMENT '是否有效';

ALTER TABLE SYS_USER MODIFY COLUMN CREATE_TIME DATETIME COMMENT '创建时间';

ALTER TABLE SYS_USER MODIFY COLUMN CREATE_BY BIGINT COMMENT '创建者';

ALTER TABLE SYS_USER MODIFY COLUMN UPDATE_TIME DATETIME COMMENT '更新时间';

ALTER TABLE SYS_USER MODIFY COLUMN UPDATE_BY BIGINT COMMENT '更新者';

